### ISSUE TITLE
URL in Event Label

### ISSUE THREAD

**Issue by SarahMcG450** [lunametrics/gascroll#1]
Hi Dan,

Is there a way to modify the code so that the full URL is pulled into GA as the Event Label? I'm seeing a truncated URL - only the end is displayed as the Event Label.

Thanks for this plugin! We've installed many ga scroll plugins and tags, and this is the only one that has displayed data in GA.

Thanks,
Sarah

**Comment by DanWilkerson** [comment]
Hi Sarah,

If you're using GTM, you can just change the GA Event Tag - if you're using hard-coded Analytics, there's a config value for that:

https://github.com/lunametrics/gascroll#label

Dan
