### ISSUE TITLE
use with single page app in GTM

### ISSUE THREAD

**Issue by Burzmalian** [lunametrics/gascroll#3]
Hello,

How would one use this in an spa, using gtm, currently using history change events for page views?

Any help would be much appreciated!  thank you.

**Comment by Burzmalian** [comment]
Thank you for the quick response!   Maybe i can reset the dataLayer ""scrollTracking" to undefined after each history change, and then the events would fire again?   I might have to modify the event to grab the current url tho.   

Does the script only fire the events when scrolling down?   would it fire them again if scrolling back up the page?

Thank you very much!

**Comment by DanWilkerson** [comment]
Unfortunately that won't fix the issue - there's an internal state that needs to be reset (cache) which isn't publically accessible. To answer your second question, no; it only fires on the way down.

**Comment by jreidel** [comment]
Hi Dan,

excellent script. Do you have SPA support on the "roadmap"?

Thanks,
Jorn

**Comment by DanWilkerson** [comment]
No set timeline, unfortunately.

**Comment by DanWilkerson** [comment]
#6 v2.0.0 is out and adds a `.reset()` method which can be used to re-calculate the distances and reset the internal cache. Docs are not in place yet, but will be forthcoming.

**Comment by DanWilkerson** [comment]
Docs are up on lunametrics.com - there's a link in the README.md file on this repo.
