### ISSUE TITLE
Event action/label not correct

### ISSUE THREAD

**Issue by maxime-pico** [lunametrics/gascroll#8]
Hey!

First thanks for your awesomeness.

I tried importing your json today but here's what I get in my real time event report:
<img width="975" alt="screen shot 2017-10-14 at 13 10 34" src="https://user-images.githubusercontent.com/4660085/31575196-24922a8a-b0e1-11e7-8650-8f2b5bb31ae4.png">

I believe there's a mixup in your new version in the variables you pass as Event Action and Event Label. However I didn't dig further to pinpoint the error.

I tried importing a previous version of your code ([this one to be precise](https://github.com/lunametrics/gascroll/blob/5ec504eb36a3bb0ba9ec9657522f05d071e71d3f/package.json)) and it doesn't have the issue I mentioned.

Hope you find the problem, in the meanwhile I'm using the older version.

Cheers

**Comment by DanWilkerson** [comment]
Hi Maxime,

Yes, this is incorrect; thank you for pointing this out. There will be a fix in next week.

Dan

**Comment by DanWilkerson** [comment]
@maxime-pico Fixed and released; thanks again!

**Comment by maxime-pico** [comment]
Awesome 👍
And it's my pleasure! Your articles helped me so many times in the last months...
